relimg/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^relimgApp/', include('relimgApp.urls'))
]

relimgApp/urls.py
from django.conf.urls import patterns, url
from relimgApp import views
from django.conf import settings

urlpatterns = patterns(
	'',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<anime_id>\d+)/$', views.details, name='details'),
	url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_URL_IMAGE,})
)

relimgApp/models.py
# coding: utf-8

from django.db import models
from django.conf import settings

# Create your models here.
class Anime(models.Model):
	CONDITION_ANIME = (
		('E', 'En emisión'),
		('F', 'Finalizado'),
	)
	TYPE_ANIME = (
		('O', 'OVA'),
		('F', 'Película'),
		('A', 'Anime'),
	)
	title = models.CharField(max_length=255,default='')
	condition = models.CharField(max_length=1, choices=CONDITION_ANIME)
	type_anime = models.CharField(max_length=1, choices=TYPE_ANIME)
	description = models.CharField(max_length=10000,default='',blank=True,null=True)
	image_media = models.ImageField(upload_to=settings.STATIC_URL_IMAGE,max_length=255,blank=True,null=True)
	image_BD = models.CharField(max_length=255,default='',blank=True,null=True)
	date = models.DateTimeField('date')

	def __str__(self):
		return "%s" % self.title

	def save(self, *args, **kwargs):
		if  self.image_media:
			nombre = self.image_media.url.split('/')[-1]
			self.image_BD = nombre
		super(Anime, self).save(*args, **kwargs)

class Categorie(models.Model):
	anime = models.ForeignKey(Anime)
	categories = models.CharField(max_length=255,default='')
	date = models.DateTimeField('date')

	def __str__(self):
		return "%s" % self.anime

relimgApp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.conf import settings
from relimgApp.models import *

# Create your views here.
def index(request):
	anime_list = Anime.objects.order_by('title')
	context = {'anime_list' : anime_list}
	return render (request, 'index.html', context)

def details(request, anime_id):
	anime = get_object_or_404(Anime, pk=anime_id)
	context = {'anime' : anime, 'STATIC_URL' : settings.STATIC_URL}
	return render (request, 'details.html', context)
	#return HttpResponse('Ahora estas mirando el anime con ID: ' + anime_id)

relimgApp/templates/details.html
{% extends 'layouts/main.html' %}
{% load staticfiles %}

{% block content %}
	<h1 class="lead"><span class="text-danger">{{detail_title}}</span> <span>{{ anime.title }}</span></h1>

	<p class="lead text-justify"><span class="text-danger">{{ detail_type }}</span> <span>{{ anime.get_type_anime_display }}</span></p>
	<p class="lead text-justify"><span class="text-danger">{{ detail_state }}</span> <span>{{ anime.get_condition_display }}</span></p>
	<p class="lead text-justify"><span class="text-danger">{{ detail_description }}</span> <span>{{ anime.description }}</span></p>

	{% for categorie in anime.categorie_set.all %}
		<p class="lead text-justify"><span class="text-danger">{{ detail_categories }}</span> <span>{{ categorie.categories }}</span></p>
	{% endfor %}

	{% if anime.image_BD %}
		<img class="img-thumbnail center-block" src="{{STATIC_URL}}images/{{anime.image_BD}}">
	{% else %}
		<img class="img-thumbnail center-block" src="{% static 'images/default.jpg' %}">
	{% endif %}

{% endblock %}

relimgApp/templates/index.html
{% extends 'layouts/main.html' %}
{% load staticfiles %}

{% block content %}
	
		{% if anime_list %}
			<div class="row">
			{% for anime in anime_list %}
				<div class="col-md-4" style="margin-top:2%">
					<div class="ih-item circle effect5">
						<a href="{% url 'details' anime.id %}">
							{% if anime.image_BD %}
								<div class="img"><img src="{{STATIC_URL}}images/{{anime.image_BD}}" alt="{{anime.image_BD}}"></div>
							{% else %}
								<div class="img"><img src="{% static 'images/default.jpg' %}" alt="default.jpg"></div>
							{% endif %}

					 		<div class="info">
					 			<div class="info-back">
					            	<h3>{{ anime.title }}</h3>
					            	<p>{{ index_anime_description }}</p>
					          	</div>
							</div>
						</a>
					</div>
				</div>
			{% endfor %}
			</div>

		{% else %}

			<div class="col-xs-12 col-sm-12 col-md-12">
				<p>No hay animes disponibles</p>
			</div>
		{% endif %}

{% endblock %}

relimgApp/templates/layouts/main.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Proyecto Python & Django</title>

    <!-- Bootstrap -->
    <link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/bootstrap.theme.min.css' %}" rel="stylesheet">
    <script type="text/javascripts" src="{% static 'js/bootstrap.min.js' %}"></script>

    <link type="text/css" href="{% static 'css/ihover.css' %}" rel="stylesheet">

    <style type="text/css">
      body {
        /* Location of the image */
        background-image: url({% static 'images/fondo.jpg' %});
        
        /* Background image is centered vertically and horizontally at all times */
        background-position: center center;
        
        /* Background image doesn't tile */
        background-repeat: no-repeat;
        
        /* Background image is fixed in the viewport so that it doesn't move when 
           the content's height is greater than the image's height */
        background-attachment: fixed;
        
        /* This is what makes the background image rescale based
           on the container's size */
        background-size: cover;
        
        /* Set a background color that will be displayed
           while the background image is loading */
        background-color: #464646;
      }
    </style>

  </head>
  <body>

     <div class="container">

        <h1 style="text-align:center;padding:15px;">
          <a href="{% url 'index' %}">{{ site_title }}</a>
          <small>{{ site_subtitle }}</small>
        </h1>

    	   <!-- The main page content -->
        {% block content %}{% endblock %}


        <div style="text-align:center;padding:15px;">
          {{ site_credits }}
        </div>

	   </div>

  </body>
</html>